In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

pd.set_option('display.float_format', lambda x: '%.3f' % x)

import warnings
warnings.filterwarnings('ignore')

## Mounting to Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
os.chdir('/content/drive/MyDrive/')

## Reading the data

In [4]:
inpatient = pd.read_csv('inpatient.csv')
outpatient = pd.read_csv('outpatient.csv')

In [5]:
inpatient['BENE_ID'] = inpatient['BENE_ID'].astype(int)
outpatient['BENE_ID'] = outpatient['BENE_ID'].astype(int)
inpatient['CLM_ID'] = inpatient['CLM_ID'].astype(int)
outpatient['CLM_ID'] = outpatient['CLM_ID'].astype(int)

In [6]:
inpatient.head()

BENE_ID          CLM_ID NCH_NEAR_LINE_REC_IDENT_CD  NCH_CLM_TYPE_CD  \
0  10000010254618  10000930037831                          V               60   
1  10000010254653  10000930038030                          V               60   
2  10000010254653  10000930038031                          V               60   
3  10000010254656  10000930038162                          V               60   
4  10000010254656  10000930038162                          V               60   

  CLM_FROM_DT CLM_THRU_DT NCH_WKLY_PROC_DT  FI_CLM_PROC_DT  CLAIM_QUERY_CODE  \
0   25-Mar-15   25-Mar-15        27-Mar-15             NaN                 3   
1   24-Sep-15   24-Sep-15        25-Sep-15             NaN                 3   
2    9-May-17   10-May-17        12-May-17             NaN                 3   
3   14-Jan-17   14-Jan-17        20-Jan-17             NaN                 3   
4   14-Jan-17   14-Jan-17        20-Jan-17             NaN                 3   

  PRVDR_NUM  ...  PRCDR_DT24  ICD_PRCDR_CD25  PRCDR_DT25  IME_OP_CLM_VAL_AMT  \
0     11500  ...         NaN             NaN         NaN                   0   
1     17129  ...         NaN             NaN         NaN                   0   
2     10052  ...         NaN             NaN         NaN                   0   
3     15455  ...         NaN             NaN         NaN                   0   
4     15455  ...         NaN             NaN         NaN                   0   

  DSH_OP_CLM_VAL_AMT  CLM_UNCOMPD_CARE_PMT_AMT  CLM_LINE_NUM REV_CNTR  \
0                  0                       NaN             1      450   
1                  0                       NaN             1      450   
2                  0                       NaN             1        1   
3                  0                       NaN             1      450   
4                  0                       NaN             2      450   

   HCPCS_CD  REV_CNTR_DDCTBL_COINSRNC_CD  
0     99221                          NaN  
1     99221                          NaN  
2     99024                        3.000  
3     73610                        3.000  
4     29515                        3.000  

[5 rows x 197 columns]

In [7]:
outpatient.head()

BENE_ID          CLM_ID NCH_NEAR_LINE_REC_IDENT_CD  NCH_CLM_TYPE_CD  \
0 -10000010254618 -10000930037832                          W               40   
1 -10000010254618 -10000930037833                          W               40   
2 -10000010254618 -10000930037834                          W               40   
3 -10000010254618 -10000930037835                          W               40   
4 -10000010254618 -10000930037836                          W               40   

  CLM_FROM_DT CLM_THRU_DT NCH_WKLY_PROC_DT  FI_CLM_PROC_DT  CLAIM_QUERY_CODE  \
0   16-Mar-15   16-Mar-15        20-Mar-15             NaN                 3   
1   27-Apr-15   27-Apr-15         1-May-15             NaN                 3   
2   23-May-15   23-May-15        29-May-15             NaN                 3   
3    1-Jun-15    1-Jun-15         5-Jun-15             NaN                 3   
4   14-Jun-15   14-Jun-15        19-Jun-15             NaN                 3   

  PRVDR_NUM  ...  REV_CNTR_BENE_PMT_AMT  REV_CNTR_PTNT_RSPNSBLTY_PMT  \
0    01S023  ...                      0                     2044.970   
1    01S023  ...                      0                     2387.270   
2    01S023  ...                      0                     1734.830   
3    01S023  ...                      0                      234.310   
4    01S023  ...                      0                     2265.440   

   REV_CNTR_PMT_AMT_AMT  REV_CNTR_TOT_CHRG_AMT REV_CNTR_NCVRD_CHRG_AMT  \
0             10224.890               8179.920                   0.000   
1             11936.390               9549.120                   0.000   
2              8674.150               6939.320                   0.000   
3               154.140                192.670                   0.000   
4             11327.220               9061.780                   0.000   

   REV_CNTR_STUS_IND_CD  REV_CNTR_NDC_QTY REV_CNTR_NDC_QTY_QLFR_CD  \
0                     4               NaN                      NaN   
1                     4               NaN                      NaN   
2                     4               NaN                      NaN   
3                     4               NaN                      NaN   
4                     4               NaN                      NaN   

   RNDRNG_PHYSN_UPIN  RNDRNG_PHYSN_NPI  
0                           9999995696  
1                           9999995696  
2                           9999995696  
3                           9999995696  
4                           9999995696  

[5 rows x 162 columns]

In [8]:
inpatient['BENE_ID'] = inpatient['BENE_ID'].abs()
inpatient['CLM_ID'] = inpatient['CLM_ID'].abs()
outpatient['BENE_ID'] = outpatient['BENE_ID'].abs()
outpatient['CLM_ID'] = outpatient['CLM_ID'].abs()

In [9]:
inpatient.describe()

BENE_ID             CLM_ID  NCH_CLM_TYPE_CD  FI_CLM_PROC_DT  \
count          58066.000          58066.000        58066.000           0.000   
mean  10000010270388.379 10000930736409.174           60.000             NaN   
std             9525.039         421361.125            0.000             NaN   
min   10000010254618.000 10000930037831.000           60.000             NaN   
25%   10000010262067.000 10000930367035.000           60.000             NaN   
50%   10000010270822.000 10000930747638.500           60.000             NaN   
75%   10000010277922.000 10000931097878.750           60.000             NaN   
max   10000010288010.000 10000931486024.000           60.000             NaN   

       CLAIM_QUERY_CODE  CLM_FAC_TYPE_CD  CLM_SRVC_CLSFCTN_TYPE_CD  \
count         58066.000        58066.000                 58066.000   
mean              3.000            1.000                     1.000   
std               0.000            0.000                     0.000   
min               3.000            1.000                     1.000   
25%               3.000            1.000                     1.000   
50%               3.000            1.000                     1.000   
75%               3.000            1.000                     1.000   
max               3.000            1.000                     1.000   

       CLM_FREQ_CD  FI_NUM  CLM_PMT_AMT  ...  NCH_BENE_MDCR_BNFTS_EXHTD_DT_I  \
count    58066.000   0.000    58066.000  ...                           0.000   
mean         1.000     NaN    13638.308  ...                             NaN   
std          0.000     NaN    35993.908  ...                             NaN   
min          1.000     NaN       62.440  ...                             NaN   
25%          1.000     NaN      945.370  ...                             NaN   
50%          1.000     NaN     1481.715  ...                             NaN   
75%          1.000     NaN     9932.040  ...                             NaN   
max          1.000     NaN   598716.310  ...                             NaN   

       CLM_DRG_CD  CLM_DRG_OUTLIER_STAY_CD  NCH_DRG_OUTLIER_APRVD_PMT_AMT  \
count   54804.000                58066.000                      58066.000   
mean      766.073                    0.066                          0.000   
std       302.210                    0.358                          0.000   
min         8.000                    0.000                          0.000   
25%       566.000                    0.000                          0.000   
50%       951.000                    0.000                          0.000   
75%       951.000                    0.000                          0.000   
max       976.000                    2.000                          0.000   

       IME_OP_CLM_VAL_AMT  DSH_OP_CLM_VAL_AMT  CLM_UNCOMPD_CARE_PMT_AMT  \
count           58066.000           58066.000                     0.000   
mean                0.000               0.000                       NaN   
std                 0.000               0.000                       NaN   
min                 0.000               0.000                       NaN   
25%                 0.000               0.000                       NaN   
50%                 0.000               0.000                       NaN   
75%                 0.000               0.000                       NaN   
max                 0.000               0.000                       NaN   

       CLM_LINE_NUM  REV_CNTR  REV_CNTR_DDCTBL_COINSRNC_CD  
count     58066.000 58066.000                    49768.000  
mean          3.341   334.189                        2.898  
std           3.051   196.437                        0.320  
min           1.000     1.000                        0.000  
25%           1.000     1.000                        3.000  
50%           2.000   450.000                        3.000  
75%           5.000   450.000                        3.000  
max          46.000   450.000                        3.000  

[8 rows x 56 columns]

In [10]:
outpatient.describe()

BENE_ID             CLM_ID  NCH_CLM_TYPE_CD  FI_CLM_PROC_DT  \
count         575092.000         575092.000       575092.000           0.000   
mean  10000010270877.461 10000930757760.621           40.000             NaN   
std             9440.354         416776.239            0.000             NaN   
min   10000010254618.000 10000930037832.000           40.000             NaN   
25%   10000010262643.000 10000930398556.750           40.000             NaN   
50%   10000010270930.000 10000930755574.500           40.000             NaN   
75%   10000010278418.000 10000931118833.500           40.000             NaN   
max   10000010288010.000 10000931486354.000           40.000             NaN   

       CLAIM_QUERY_CODE  CLM_FAC_TYPE_CD  CLM_SRVC_CLSFCTN_TYPE_CD  \
count        575092.000       575092.000                575092.000   
mean              3.000            1.000                     3.000   
std               0.000            0.000                     0.000   
min               3.000            1.000                     3.000   
25%               3.000            1.000                     3.000   
50%               3.000            1.000                     3.000   
75%               3.000            1.000                     3.000   
max               3.000            1.000                     3.000   

       CLM_FREQ_CD  FI_NUM  CLM_PMT_AMT  ...  REV_CNTR_PRVDR_PMT_AMT  \
count   575092.000   0.000   575092.000  ...              575092.000   
mean         1.000     NaN     2374.190  ...                2374.190   
std          0.000     NaN     8425.517  ...                8425.517   
min          1.000     NaN       59.640  ...                  59.640   
25%          1.000     NaN      704.620  ...                 704.620   
50%          1.000     NaN     1003.705  ...                1003.705   
75%          1.000     NaN     1355.653  ...                1355.653   
max          1.000     NaN   428631.860  ...              428631.860   

       REV_CNTR_BENE_PMT_AMT  REV_CNTR_PTNT_RSPNSBLTY_PMT  \
count             575092.000                   575092.000   
mean                   0.000                      349.124   
std                    0.000                     1366.228   
min                    0.000                        0.000   
25%                    0.000                        0.000   
50%                    0.000                      136.610   
75%                    0.000                      245.330   
max                    0.000                    66744.090   

       REV_CNTR_PMT_AMT_AMT  REV_CNTR_TOT_CHRG_AMT  REV_CNTR_NCVRD_CHRG_AMT  \
count            575092.000             575092.000               575092.000   
mean                954.679               1056.036                   95.974   
std                4746.968               5146.225                 1726.909   
min                   0.000                  0.000                    0.000   
25%                   0.000                  0.000                    0.000   
50%                 385.360                533.790                    0.000   
75%                 786.263                923.200                    0.000   
max              428547.100             428547.100               410945.850   

       REV_CNTR_STUS_IND_CD  REV_CNTR_NDC_QTY  REV_CNTR_NDC_QTY_QLFR_CD  \
count            575092.000             0.000                     0.000   
mean                  4.000               NaN                       NaN   
std                   0.000               NaN                       NaN   
min                   4.000               NaN                       NaN   
25%                   4.000               NaN                       NaN   
50%                   4.000               NaN                       NaN   
75%                   4.000               NaN                       NaN   
max                   4.000               NaN                       NaN   

       RNDRNG_PHYSN_NPI  
count        575092.000  
mean     9999985735.833  


## Selecting requred columns

In [11]:
var = ['BENE_ID', 'CLM_ID', 'PRVDR_STATE_CD', 'PRVDR_NUM','PRNCPAL_DGNS_CD', 'CLM_TOT_CHRG_AMT', 'CLM_E_POA_IND_SW1' ]



In [12]:
print('inpatient columns :')
incol = []
for i in inpatient.columns:
  if i in var:
    incol= incol +[i]



inpatient columns :


In [13]:
print('outpatient columns :')
outcol = []
for i in outpatient.columns:
  if i in var:
    outcol = outcol + [i]

outpatient columns :


In [14]:
inpatient = inpatient[incol]
outpatient = outpatient[outcol]

In [15]:
inpatient['PATIENT_TYPE'] = 1
outpatient['PATIENT_TYPE'] = 0

In [16]:
inpatient

BENE_ID          CLM_ID PRVDR_NUM  PRVDR_STATE_CD  \
0      10000010254618  10000930037831     11500               1   
1      10000010254653  10000930038030     17129               1   
2      10000010254653  10000930038031     10052               1   
3      10000010254656  10000930038162     15455               1   
4      10000010254656  10000930038162     15455               1   
...               ...             ...       ...             ...   
58061  10000010288008  10000931485965     50243               5   
58062  10000010288008  10000931485967     56428               5   
58063  10000010288008  10000931485969     56428               5   
58064  10000010288008  10000931485971     50243               5   
58065  10000010288010  10000931486024    555851               5   

       CLM_TOT_CHRG_AMT PRNCPAL_DGNS_CD CLM_E_POA_IND_SW1  PATIENT_TYPE  
0                96.650          S134XX                 Y             1  
1              6311.880           Z3480                 U             1  
2              8545.720          T7432X                 Y             1  
3              1014.850          S8290X                 Y             1  
4              1014.850          S8290X                 Y             1  
...                 ...             ...               ...           ...  
58061           166.970         T50901A                 Y             1  
58062           166.970         T50901A                 Y             1  
58063           166.970         T50901A                 Y             1  
58064           166.970         T50901A                 Y             1  
58065           166.970          S93409                 Y             1  

[58066 rows x 8 columns]

In [17]:
outpatient

BENE_ID          CLM_ID PRVDR_NUM  PRVDR_STATE_CD  \
0       10000010254618  10000930037832    01S023               1   
1       10000010254618  10000930037833    01S023               1   
2       10000010254618  10000930037834    01S023               1   
3       10000010254618  10000930037835    01S023               1   
4       10000010254618  10000930037836    01S023               1   
...                ...             ...       ...             ...   
575087  10000010288007  10000931486350     50789               5   
575088  10000010288007  10000931486351     50789               5   
575089  10000010288007  10000931486352     50789               5   
575090  10000010288007  10000931486353     50789               5   
575091  10000010288007  10000931486354     50789               5   

        CLM_TOT_CHRG_AMT PRNCPAL_DGNS_CD  PATIENT_TYPE  
0              10224.890           R4689             0  
1              11936.390           R4689             0  
2               8674.150           R4689             0  
3               1171.570           R4689             0  
4              11327.220           R4689             0  
...                  ...             ...           ...  
575087           326.650            Z940             0  
575088           272.700            Z940             0  
575089           272.700            Z940             0  
575090            82.020          S5290X             0  
575091         15115.260          S5290X             0  

[575092 rows x 7 columns]

In [18]:
c = outpatient['BENE_ID'].isin(inpatient['BENE_ID'])

In [19]:
outpatient=outpatient[c]

In [20]:
outpatient['PRVDR_STATE_CD'].unique()

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53,  5])

In [21]:
inpatient.dropna(inplace = True)

## Creating number of claims columns

In [22]:
inpatient['Number_of_Claims'] = inpatient.groupby(['BENE_ID', 'PRNCPAL_DGNS_CD', 'CLM_E_POA_IND_SW1', 'PRVDR_STATE_CD'])['CLM_TOT_CHRG_AMT'].transform('count')
outpatient['Number_of_Claims'] = outpatient.groupby(['BENE_ID', 'PRNCPAL_DGNS_CD', 'PRVDR_STATE_CD'])['CLM_TOT_CHRG_AMT'].transform('count')

In [23]:
inpatient['Number_of_Claims'].unique()

array([  1,   2,   3,   6,  12,  14,  13,  11,   8,   7,   4,  15,  16,
         5,   9,  34,  10,  21,  20, 271,  93,  76,  26,  44,  62,  30,
        28,  18,  17,  68,  31,  38,  48,  24,  32,  19,  29,  25,  49,
        43,  39,  45, 154,  22, 174,  36, 142,  41, 120, 122,  23,  27,
        35,  61, 128,  58, 160,  69,  73, 168,  54, 162, 112,  42,  72,
       104,  78,  50, 127, 111,  33,  77,  65, 202, 138,  98, 223,  52,
        66,  59,  40])

In [24]:
outpatient['Number_of_Claims'].unique()

array([ 22,  36,   3,  16,  11,   6,  15,   8,   1,   2,  18,  21,  12,
       470,   4,  94,  17,   5, 384, 158,   7,  23, 138, 107,  10,  14,
        13,  24,  25,  26, 176,  37,  27,  19,  56, 124,  20,  43, 195,
       148, 116, 364, 323,   9, 106,  45, 376,  34,  41,  67,  38,  30,
        70,  39,  62,  33, 230,  31,  84, 493, 199,  61,  28, 134,  32,
       594,  58,  35, 172, 115,  65,  79,  68, 164, 487,  69,  55,  74,
        78,  76,  92, 270, 425,  83,  90,  29,  47, 438, 205, 260,  54,
       637,  44, 437,  42, 119, 264,  52, 109, 433,  40, 123, 110, 141,
       169, 447, 224, 714, 310, 151, 395, 348, 312,  96, 321, 233, 183,
        51, 474, 159, 291, 387,  49, 306, 180,  97, 292, 415, 909, 105,
       182,  85, 153,  87, 168, 344, 525,  48,  66, 173, 333,  63, 258,
       114, 175, 244, 210, 342, 179, 157, 242,  81, 239, 221, 178, 243,
       214,  53, 140, 650,  64, 126,  80, 162, 129, 332, 467, 635,  60,
       120, 460, 177, 450,  50, 108, 515, 368, 381, 194, 584, 11

In [25]:
agg_data_inp = inpatient.groupby(['BENE_ID', 'PRNCPAL_DGNS_CD','CLM_E_POA_IND_SW1','PRVDR_STATE_CD','Number_of_Claims'])['CLM_TOT_CHRG_AMT'].sum().reset_index()
agg_data_out = outpatient.groupby(['BENE_ID', 'PRNCPAL_DGNS_CD','PRVDR_STATE_CD','Number_of_Claims'])['CLM_TOT_CHRG_AMT'].sum().reset_index()



# Merging datasets

In [26]:
# Merging agg_data_inp and agg_data_out based on beneficiary_id
merged_data = pd.merge(agg_data_inp, agg_data_out, on='BENE_ID', suffixes=('_inp', '_out'))

In [27]:
merged_data.drop_duplicates()

BENE_ID PRNCPAL_DGNS_CD_inp CLM_E_POA_IND_SW1  \
0      10000010254618              S134XX                 Y   
1      10000010254618              S134XX                 Y   
2      10000010254618              S134XX                 Y   
3      10000010254618              S134XX                 Y   
4      10000010254653              T7432X                 Y   
...               ...                 ...               ...   
46054  10000010288008             T50901A                 Y   
46055  10000010288008             T50901A                 Y   
46056  10000010288010              S93409                 Y   
46057  10000010288010              S93409                 Y   
46058  10000010288010              S93409                 Y   

       PRVDR_STATE_CD_inp  Number_of_Claims_inp  CLM_TOT_CHRG_AMT_inp  \
0                       1                     1                96.650   
1                       1                     1                96.650   
2                       1                     1                96.650   
3                       1                     1                96.650   
4                       1                     1              8545.720   
...                   ...                   ...                   ...   
46054                   5                     8              1335.760   
46055                   5                     8              1335.760   
46056                   5                     1               166.970   
46057                   5                     1               166.970   
46058                   5                     1               166.970   

      PRNCPAL_DGNS_CD_out  PRVDR_STATE_CD_out  Number_of_Claims_out  \
0                   B9789                   1                    36   
1                     I10                   1                    16   
2                    P292                   1                     3   
3                   R4689                   1                    22   
4                    B002                   1                     1   
...                   ...                 ...                   ...   
46054             T50901A                   5                    14   
46055                Z608                   5                     9   
46056               B9789                   5                     3   
46057                J209                   5                     6   
46058                Z733                   5                     6   

       CLM_TOT_CHRG_AMT_out  
0                142077.680  
1                 30532.130  
2                  1700.790  
3                208286.070  
4                    60.700  
...                     ...  
46054              8954.780  
46055              6142.680  
46056               627.420  
46057             17065.520  
46058              9069.660  

[46059 rows x 10 columns]

In [28]:
merged_data['PRVDR_STATE_CD_inp'].unique()

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53,  5])

In [29]:
merged_data['PRVDR_STATE_CD_out'].unique()

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53,  5])

In [30]:
merged_data.CLM_E_POA_IND_SW1.unique()

array(['Y', 'U'], dtype=object)

## Writing into excel file

In [31]:
merged_data.to_excel('Patient_Claim_Data.xlsx', index = False)